service: padawan-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  createUser:
    handler: src/Handlers/user.create
    events:
      - httpApi:
          path: /user
          method: post

plugins:
  - serverless-offline
